import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { v4 as uuidv4 } from "uuid";

const handleAddToCart = () => {
  const eventName = "AddToCart";
  const eventId = uuidv4();
  const payload = {
    products: [{ id: 123, quantity: 1 }],
    value: 123,
    currency: "EUR",
  };

  window.fbq("track", eventName, payload, { eventID: eventId });

  setTimeout(() => {
    const serverSidePayload = JSON.stringify({
      eventName,
      eventId,
      userAgent: navigator.userAgent,
      sourceUrl: window.location.href,
      ...payload,
    });

    fetch("/api/fb-event", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: serverSidePayload,
    })
      .then((response) => {
        console.log("/api/fb-page-view response:", response);
      })
      .catch((error) => {
        console.error("/api/fb-page-view error:", error);
      });
  }, 250);
};

export default function Home() {
  return (
    <>
      <Head>
        <title>I-RIS - FB CAPI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Check the source at&nbsp;
            <code className={styles.code}>src/pages/index.js</code>
          </p>
        </div>

        <div>
          <button onClick={() => handleAddToCart()}>Send Event</button>
        </div>
      </main>
    </>
  );
}
